networks:
  tk:
    external: true
  database:
    external: true

volumes:
  mariadb:

services:
  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: 'portainer'
    restart: 'unless-stopped'
    networks:
      - 'tk'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './portainer:/data'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    ports:
      - '127.0.0.1:6900:9000'

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: 'nginx-proxy-manager'
    restart: 'unless-stopped'
    networks:
      - 'tk'
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '127.0.0.1:6901:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: 'mariadb'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: 'npm'
      DB_MYSQL_NAME: 'npm'
      TZ: 'America/Los_Angeles'
    volumes:
      - './data:/data'
      # - ./npm/nginx:/etc/nginx
      - './letsencrypt:/etc/letsencrypt'

  mariadb:
    image: 'linuxserver/mariadb'
    container_name: 'mariadb'
    restart: 'unless-stopped'
    networks:
      - 'tk'
      - 'database'
    volumes:
      - 'mariadb:/config'
    environment:
      PUID: '1000'
      PGID: '1000'
      MYSQL_ROOT_PASSWORD: 'npm'
      TZ: 'America/Los_Angeles'
      # nginx proxy database
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'

  phpmyadmin:
    image: 'linuxserver/phpmyadmin'
    container_name: 'phpmyadmin'
    networks:
      - 'database'
    environment:
      PUID: '1000'
      PGID: '1000'
      PMA_HOST: 'mariadb'
      PMA_USER: 'root'
      PMA_PASSWORD: 'npm'
      TZ: 'America/Los_Angeles'
    ports:
      - '127.0.0.1:6902:80'
    restart: 'unless-stopped'

  filebrowser:
    image: 'hurlenko/filebrowser'
    container_name: 'filebrowser'
    user: '1000:1000'
    ports:
      - '127.0.0.1:6903:8080'
    volumes:
      - '/home/tk:/data'
      - './filebrowser/config:/config'
    environment:
      - FB_BASEURL=/
    restart: 'unless-stopped'

  watchtower:
    image: 'containrrr/watchtower'
    container_name: 'watchtower'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: 'unless-stopped'

  fail2ban:
    image: 'crazymax/fail2ban:latest'
    container_name: 'fail2ban'
    hostname: 'fail2ban'
    cap_add:
      - 'NET_ADMIN'
      - 'NET_RAW'
    environment:
      - TZ='America/Los_Angeles'
      - F2B_DB_PURGE_AGE='3d'
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
      - './fail2ban/data:/data'
      - './data/logs:/var/log/npm'
