#!/usr/bin/bash

# vars
config='$HOME/.config/waybar/config.jsonc'
style='$HOME/.config/waybar/style.css'

# Terminate already running bar instances
killall -q waybar

# Wait until the processes have been shut down
while pgrep -x waybar >/dev/null; do sleep 1; done

# Launch main
waybar --config ${config} --style ${style}
