shell = "zsh"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = { value = 'zsh-defer source "{{ file }}"', each = true }

[plugins.zsh-term-title]
github = 'pawel-slowik/zsh-term-title'

[plugins.zsh-history-substring-search]
github = 'zsh-users/zsh-history-substring-search'

[plugins.gitstatus]
github = 'romkatv/gitstatus'
use = ['gitstatus.prompt.zsh']

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
apply = ["defer"]

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
apply = ["defer"]
hooks.post = ['''
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
''']

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath", "defer"]

[plugins.zsh-fancy-completions]
github = "z-shell/zsh-fancy-completions"
apply = ["fpath", "defer"]

[plugins.H-S-MW]
github = "z-shell/H-S-MW"
apply = ["defer"]

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"


