#!/bin/bash



#rofi -show drun \
#	-icon-theme "Papirus Dark"
#	-theme "~/.config/rofi/launchers/apps/launcher.rasi"

nwg-drawer \
	-c 7 \
	-fm 'thunar' \
	-g 'Dracula' \
	-i 'Papirus Dark' \
	-is 84 \
	-nocats \
	-o 'Hyprland' \
	-pbexit 'hyprctl dispatch exit' \
	-pblock 'hyprlock' \
	-pbpoweroff 'systemctl poweroff' \
	-pbreboot 'systemctl reboot' \
	-pbsize 48 \
	-pbsleep 'hypridle' \
	-s "drawer.css" \
	-spacing 1em 1.5em 
	
