#!/bin/bash

prev_bat=`acpi -b | grep -P -o '[0-9]+(?=%)'`

while true
do
    curr_bat=`acpi -b | grep -P -o '[0-9]+(?=%)'`
    if [[ $curr_bat -eq 100 && $prev_bat -lt 100 ]]; then
        notify-send "Fully charged" "Level: ${curr_bat}%"
    elif [[ $curr_bat -le 20 && $prev_bat -gt 20 ]]; then
        notify-send --urgency=CRITICAL "Battery Low" "Level: ${curr_bat}%"
    elif [[ $curr_bat -le 10 && $prev_bat -gt 10 ]]; then
        notify-send --urgency=CRITICAL "Battery Low" "Level: ${curr_bat}%"
    fi
    prev_bat=curr_bat
    sleep 60
done



bat="/sys/class/power_supply/BAT0/"
per="$(cat "$bat/capacity")"
chr="$(cat "$bat/status")"
   
while true
do

  icon(){
    [ "$chr" = Charging ] && echo "" && exit

    if [ "$per" -gt "100" ]; then
        icon="󰁹"
        notify-send "Fully charged" "Level: ${curr_bat}%"
    elif [ "$per" -gt "90" ]; then
        icon="󰂂"
    elif [ "$per" -gt "80" ]; then
        icon="󰂁"
    elif [ "$per" -gt "70" ]; then
        icon="󰂀"
    elif [ "$per" -gt "60" ]; then
        icon="󰁿"
    elif [ "$per" -gt "50" ]; then
        icon="󰁾"
    elif [ "$per" -gt "40" ]; then
        icon="󰁽"
    elif [ "$per" -gt "30" ]; then
        icon="󰁼"
    elif [ "$per" -gt "20" ]; then
        icon="󰁻"
        notify-send -u critical "Battery Low" "Connect Charger"
    elif [ "$per" -gt "10" ]; then
        icon="󰁺"
        notify-send -u critical "Battery Low" "Connect Charger"
    elif [ "$per" -gt "0" ]; then
        icon="󰂎"
        notify-send -u critical "Battery Low"   "Connect Charger"
    else
        echo  && exit
    fi
    echo "$icon"
  >}


    percent() {
        echo "$per"
    }

    [ "$1" = "icon" ] && icon && exit
    [ "$1" = "percent" ] && percent && exit
done