#!/usr/bin/env bash

nwg-drawer -c 6 -fm Thunar -ft Dracula -i Papirus-Dark -is 72 -nocats -nofs -ovl -pbexit "hyprctl dispatch exit" -pblock hyprlock -pbpoweroff "systemctl poweroff -i" -pbreboot "systemctl reboot -i" -pbsize 48 -pbsleep "systemctl suspend -i" -s style.css


	
