#!/usr/bin/env bash

icon_package="$HOME/.local/bin/notifications/icons/package-update.png"

num_updates=$(checkupdates | wc -l)
if [[ $num_updates -gt 0 ]]; then
    notify-send -i "$icon_package" -u normal -r 60 "Available updates" "$num_updates package(s) require updating."
fi
