#!/bin/bash

SCRIPTSDIR="$HOME/.config/hypr/scripts"

# Lauch notification daemon (mako)
"$SCRIPTSDIR/notifications &"

# wallpaper
"$SCRIPTSDIR/wallpaper &"

# themes
"$SCRIPTSDIR/gtkthemes &"

# systemd configuration
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 

# portals
"$SCRIPTSDIR/hyprland-portal &"

# waybar
"$SCRIPTSDIR/statusbar &"

# bluetooth
"blueman-applet &"

# network
"nm-applet --indicator &"

# polkit
"/usr/lib/polkit-kde-authentication-agent-1 &"

# app launcher
"nwggrid-server &"

# foot
"foot -s &"

