#!/usr/bin/bash

SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# wallpaper
${SCRIPTSDIR}/wallpaper &

# themes
${SCRIPTSDIR}/gtkthemes & 

# portals
${SCRIPTSDIR}/portal-arch-hyprland &

# waybar
${SCRIPTSDIR}/statusbar &

# startup
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP &

# bluetooth
blueman-applet &

# network
nm-applet --indicator &

# polkit
/usr/lib/polkit-kde-authentication-agent-1 &

# app launcher
nwggrid-server &

# foot
foot -s &

